name: Psalm Static Analysis

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: "30 0 * * *" # daily at 00:30 UTC

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1" # or your desired PHP version >=8.0
          tools: composer

      - name: Install dependencies with Composer
        run: composer install --no-progress --no-interaction --prefer-dist

      - name: Generate Psalm config file (if missing)
        run: |
          if [ ! -f psalm.xml ]; then
            ./vendor/bin/psalm --init
          else
            echo "psalm.xml already exists, skipping generation."
          fi

      - name: Run Psalm static analysis
        run: ./vendor/bin/psalm --show-info=false --output-format=github
