name: Psalm Static Analysis

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: "30 0 * * *" # daily at 00:30 UTC

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Psalm
        run: |
          curl -sSL https://github.com/vimeo/psalm/releases/latest/download/psalm.phar -o psalm.phar
          chmod +x psalm.phar

      - name: Generate Psalm config file (if missing)
        run: |
          if [ ! -f psalm.xml ]; then
            ./psalm.phar --init
          else
            echo "psalm.xml already exists, skipping generation."
          fi

      - name: Run Psalm static analysis
        run: ./psalm.phar --show-info=false --output-format=github
