name: Psalm Static Analysis

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]
  schedule:
    - cron: "30 0 * * *" # Runs daily at 00:30 UTC

jobs:
  psalm:
    name: Run Psalm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2" # Adjust this to your project's PHP version

      - name: Install dependencies
        run: composer install --no-progress --no-suggest --prefer-dist

      - name: Run Psalm
        run: vendor/bin/psalm --output-format=github
